# Generated by Django 4.0.5 on 2022-07-06 16:55

from django.db import migrations


def delete_all_posts(apps, schema_editor) -> None:
    Post = apps.get_model("blog", "Post")
    Post.objects.filter().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_post_image_post_category'),
    ]

    operations = [
        migrations.RunPython(delete_all_posts)
    ]
