# Generated by Django 4.0.5 on 2022-08-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(through='blog.TagOfPost', to='blog.tag'),
        ),
    ]
