# Generated by Django 4.0.5 on 2022-07-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "blogger", "verbose_name_plural": "bloggers"},
        ),
    ]
