# Generated by Django 4.0.5 on 2022-08-03 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_post_category"),
        ("mails", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="category",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="blog.category"
            ),
        ),
    ]
